# Generated by Django 6.0.3 on 2026-04-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('intern', 'INTERN'), ('extern', 'EXTERN')], max_length=50)),
                ('status', models.CharField(choices=[('assigned', 'ASSIGNED'), ('notassigned', 'NOTASSIGNED')], default='notassigned', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('M', 'must'), ('N', 'need'), ('L', 'low')], max_length=50)),
                ('status', models.CharField(choices=[('APPROVED', 'approved'), ('DENIED', 'denied'), ('WAITING', 'waiting')], default='WAITING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='TrainingNeed_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingneed'),
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('APPROVED', 'approved'), ('DENIED', 'denied')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('TrainingNeed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingneed')),
            ],
        ),
    ]
