# Generated by Django 6.0.3 on 2026-04-25 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'draft'), ('SENT', 'sent')], default='DRAFT', max_length=50)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('M', 'must'), ('N', 'need'), ('L', 'low')], max_length=50)),
                ('status', models.CharField(choices=[('APPROVED', 'approved'), ('DENIED', 'denied'), ('WAITING', 'waiting')], default='WAITING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingform')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('intern', 'INTERN'), ('extern', 'EXTERN')], max_length=50)),
                ('status', models.CharField(choices=[('assigned', 'ASSIGNED'), ('notassigned', 'NOTASSIGNED')], default='notassigned', max_length=100)),
                ('TrainingNeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingneed')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('APPROVED', 'approved'), ('DENIED', 'denied')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('TrainingNeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingneed')),
            ],
        ),
    ]
