# Generated by Django 6.0.3 on 2026-04-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('APPROVED', 'approved'), ('DENIED', 'denied')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('intern', 'INTERN'), ('extern', 'EXTERN')], max_length=50)),
                ('status', models.CharField(choices=[('assigned', 'ASSIGNED'), ('notassigned', 'NOTASSIGNED')], default='notassigned', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('finalDate', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'draft'), ('SENT', 'sent')], default='DRAFT', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('M', 'must'), ('N', 'need'), ('L', 'low')], max_length=50)),
                ('status', models.CharField(choices=[('APPROVED', 'approved'), ('DENIED', 'denied'), ('WAITING', 'waiting')], default='WAITING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
