# Generated by Django 6.0.3 on 2026-04-26 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingform',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingneed',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingneed',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingform'),
        ),
        migrations.AddField(
            model_name='training',
            name='TrainingNeed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingneed'),
        ),
        migrations.AddField(
            model_name='decision',
            name='TrainingNeed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingneed'),
        ),
    ]
