# Generated by Django 6.0.3 on 2026-05-04 18:08

import training.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingform',
            name='finalDate',
            field=models.DateField(default=training.models.default_final_date),
        ),
    ]
