# Generated by Django 6.0.3 on 2026-05-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_trainingform_finaldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingform',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('SENT', 'sent'), ('HANDLED', 'handled')], default='DRAFT', max_length=50),
        ),
    ]
